# -*- coding: utf-8 -*-
"""app_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eyoiGlyqYEPJWWYbCrmWYxKxpR4SY60g
"""

import io, zipfile
import numpy as np
from PIL import Image, ImageDraw
import streamlit as st
import os, tempfile, importlib.util, types
import requests
import torch
import tempfile
import gdown

import tempfile

import modelyolo4
import torch

import modelyolo4full

import training_core
import pandas as pd
import os

# לציור גרפים מובנים של Streamlit
import matplotlib.pyplot as plt
from training_core import run_training_only_train


# ===================== בסיס ועיצוב =====================
st.set_page_config(page_title="Lung Nodule System", layout="wide")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
FULL_MODEL_URL = "https://drive.usercontent.google.com/uc?id=1zvhTiigngEF5QHH5M8-QSZn18C6SiSNp&export=download"


FULL_MODEL_URL = "https://drive.usercontent.google.com/uc?id=1zvhTiigngEF5QHH5M8-QSZn18C6SiSNp&export=download"

@st.cache_resource(show_spinner=True)
def load_full_model_from_url(url: str):
    import io, requests
    with st.spinner("מוריד/טוען מודל מלא..."):
        r = requests.get(url, timeout=300)
        r.raise_for_status()
        buf = io.BytesIO(r.content)
        # PyTorch 2.6 דורשת לציין במפורש weights_only=False לטעינה של מודל מלא
        m = torch.load(buf, map_location=device, weights_only=False)
        m.to(device).eval()
        return m


# מזהה הקובץ בדרייב (אפשר גם לתת URL; הפונקציה תטפל)
FULL_MODEL_ID = "1Qx4POlUFdoLmtv0lPuq-Cd8KP86X5LKo"
@st.cache_resource(show_spinner="מוריד/טוען מודל מלא...")
def load_full_model_from_drive(url_or_id):
    import io, torch

    # 1) הורדה חסינה מדרייב (כולל confirm-token). משתמש בפונקציה שכבר אצלך.
    raw = _gdrive_download_bytes(url_or_id)

    # 2) הגנה מפני HTML שמתחזה לקובץ בינארי – גורם ל-"invalid load key, '<'"
    head = raw[:256].lower()
    if b"<html" in head or b"<!doctype html" in head or head[:1] == b"<":
        preview = raw[:200].decode("utf-8", errors="ignore")
        raise RuntimeError("Google Drive החזיר HTML במקום קובץ בינארי. בדקי שיתוף וקישור. תצוגה ראשונית:\n" + preview)

    # 3) ניסיון טעינה: קודם ברירת-מחדל (ב-PyTorch 2.6 זה weights_only=True),
    #    ואם נכשל (Unsupported operand / Pickle) ננסה weights_only=False.
    buf = io.BytesIO(raw)
    try:
        obj = torch.load(buf, map_location=device)
    except Exception as e1:
        buf.seek(0)
        try:
            obj = torch.load(buf, map_location=device, weights_only=False)
        except Exception as e2:
            raise RuntimeError("טעינת מודל נכשלה גם לאחר weights_only=False.\nשגיאה 1: {}\nשגיאה 2: {}".format(e1, e2))

    # 4) אם זה state_dict – נבנה מודל ונעמיס לתוכו. אם זה מודול – פשוט להחזיר.
    if isinstance(obj, dict):
        # זה state_dict: חייבים build_model מהקוד שלך
        model = build_model().to(device)
        model.load_state_dict(obj, strict=False)  # strict=False כדי לא להיתקע על מפתחות שוליים
        model.eval()
        return model

    if not isinstance(obj, torch.nn.Module):
        raise RuntimeError("האובייקט שנטען אינו torch.nn.Module ואינו state_dict. ודאי שהקובץ נכון.")

    obj.to(device).eval()
    return obj







THEME_CSS = """
<style>
html, body, [data-testid="stAppViewContainer"] { background-color: #E6F4FF; color: #000; }
[data-testid="stHeader"], [data-testid="stToolbar"] { background: transparent; }
[data-testid="stSidebar"] { background-color: #E6F4FF !important; }
h1 { font-size: 34px !important; font-weight: 800; color:#003366 !important; }
h2 { font-size: 28px !important; font-weight: 700; color:#003366 !important; }
h3 { font-size: 28px !important; font-weight: 700; color:#003366 !important; }
h4, h5, h6 { color: #003366 !important; }
p, span, label, div { font-size: 20px !important; color:#000 !important; }

/* כפתורים גדולים */
.stButton > button, .stDownloadButton > button {
    font-size: 22px !important;
    line-height: 1.2 !important;
    font-weight: 600 !important;
    padding: 16px 16px !important;
    border-radius: 12px !important;
    background-color: #ffffff !important;
    color: #003366 !important;
    border: 2px solid #003366 !important;
    transition: all 0.15s ease-in-out !important;
}

/* כפתורי Back: כל כפתור מסוג secondary יהיה “לינק” */
[data-testid="baseButton-secondary"] {
    background: transparent !important;
    border: none !important;
    color: #003366 !important;
    text-decoration: underline !important;
    box-shadow: none !important;
    padding: 0 !important;
    font-size: 20px !important;
    font-weight: 600 !important;
    line-height: 1.2 !important;
}

/* חשוב: לא לשבור את שאר הכפתורים (primary) */
[data-testid="baseButton-primary"] {
    font-size: 22px !important;
    line-height: 1.2 !important;
    font-weight: 600 !important;
    padding: 16px 16px !important;
    border-radius: 12px !important;
    background-color: #ffffff !important;
    color: #003366 !important;
    border: 2px solid #003366 !important;
    transition: all 0.15s ease-in-out !important;
}


/* חשוב: הילדים בתוך הכפתור יורשים את הגודל של הכפתור */
.stButton > button *, .stDownloadButton > button * {
    font-size: inherit !important;
}


.center { text-align:center; }
.subtle { color:#003366; }
.hr { border-top:1px solid rgba(0,0,0,0.15); margin: 0.5rem 0 1rem; }
</style>
"""
st.markdown(THEME_CSS, unsafe_allow_html=True)

if "page" not in st.session_state:
    st.session_state.page = "home"

# ===================== קישורים לקוד המודל ולמשקלים =====================
# דוגמה: https://drive.google.com/uc?id=<FILE_ID>
#MODEL_PY_URL = "https://drive.google.com/uc?export=download&id=19M7TwXrQXFJ-UqJ-4v3lul6JmSNgYa9w"

#WEIGHTS_URL = "https://drive.google.com/uc?export=download&id=1poyGTKmN_CS4qdSbKaAtJ_MaoOQfnr2R"

# ===== Direct-download (no HTML interstitial) =====
#MODEL_PY_URL = "https://drive.usercontent.google.com/uc?id=19M7TwXrQXFJ-UqJ-4v3lul6JmSNgYa9w&export=download"
#WEIGHTS_URL  = "https://drive.usercontent.google.com/uc?id=1poyGTKmN_CS4qdSbKaAtJ_MaoOQfnr2R&export=download"
MODEL_PY_URL = "19M7TwXrQXFJ-UqJ-4v3lul6JmSNgYa9w"
WEIGHTS_URL  = "1poyGTKmN_CS4qdSbKaAtJ_MaoOQfnr2R"


# ===================== Utilities למסך ה-TEST =====================



def slice_to_pil(arr2d, vmin=None, vmax=None):
    import numpy as np
    from PIL import Image
    arr = arr2d.astype(np.float32)
    if vmin is None or vmax is None:
        lo, hi = np.percentile(arr, [2, 98])
    else:
        lo, hi = float(vmin), float(vmax)
    if hi <= lo:
        lo, hi = float(arr.min()), float(arr.max())
    arr = np.clip((arr - lo) / max(hi - lo, 1e-6), 0.0, 1.0)
    return Image.fromarray((arr * 255).astype(np.uint8), mode="L").convert("RGB")

def clamp(val, lo, hi):
    return int(max(lo, min(hi, val)))

def draw_square(drw: ImageDraw.ImageDraw, cx, cy, diam, color=(0,255,0)):
    r = diam/2.0
    drw.rectangle([(cx-r, cy-r), (cx+r, cy+r)], outline=color, width=2)

def infer_order(arr, Z, Y, X):
    if arr is None or arr.size == 0 or arr.ndim != 2 or arr.shape[1] != 5:
        return "zyx"
    def score(order):
        cnt = 0
        for row in arr:
            if order == "zyx":
                z, y, x = row[1], row[2], row[3]
            else:
                x, y, z = row[1], row[2], row[3]
            if (0 <= z < Z) and (0 <= y < Y) and (0 <= x < X):
                cnt += 1
        return cnt
    return "zyx" if score("zyx") >= score("xyz") else "xyz"

def parse_boxes(arr, Z, Y, X):
    boxes = []
    if arr is None or arr.size == 0: return boxes, "zyx"
    if arr.ndim != 2 or arr.shape[1] != 5:
        st.warning("⚠️ labels/preds חייבים להיות בצורה (N,5). מדלגת.")
        return boxes, "zyx"
    order = infer_order(arr, Z, Y, X)
    for row in arr:
        cls = int(row[0])
        if order == "zyx":
            z, y, x, d = float(row[1]), float(row[2]), float(row[3]), float(row[4])
        else:
            x, y, z, d = float(row[1]), float(row[2]), float(row[3]), float(row[4])
        boxes.append((z, y, x, d, cls))
    return boxes, order

def to_box_coords(z, y, x, d):
    r = d/2.0
    return (z-r, z+r, y-r, y+r, x-r, x+r)

def iou3d(b1, b2):
    z0a,z1a,y0a,y1a,x0a,x1a = b1
    z0b,z1b,y0b,y1b,x0b,x1b = b2
    iz = max(0.0, min(z1a,z1b) - max(z0a,z0b))
    iy = max(0.0, min(y1a,y1b) - max(y0a,y0b))
    ix = max(0.0, min(x1a,x1b) - max(x0a,x0b))
    inter = iz*iy*ix
    vol_a = (z1a-z0a)*(y1a-y0a)*(x1a-x0a)
    vol_b = (z1b-z0b)*(y1b-y0b)*(x1b-x0b)
    union = vol_a + vol_b - inter
    return 0.0 if union <= 0 else inter/union

def match_greedy(gt_boxes, pd_boxes, iou_thr=0.1):
    gt_coords = [to_box_coords(*b[:4]) for b in gt_boxes]
    pd_coords = [to_box_coords(*b[:4]) for b in pd_boxes]
    used_gt, used_pd, matches, cand = set(), set(), [], []
    for gi, gc in enumerate(gt_coords):
        for pi, pc in enumerate(pd_coords):
            iou = iou3d(gc, pc)
            if iou >= iou_thr: cand.append((iou, gi, pi))
    cand.sort(reverse=True)
    for iou, gi, pi in cand:
        if gi in used_gt or pi in used_pd: continue
        used_gt.add(gi); used_pd.add(pi); matches.append((gi, pi, iou))
    unmatched_gt = [i for i in range(len(gt_boxes)) if i not in used_gt]
    unmatched_pd = [i for i in range(len(pd_boxes)) if i not in used_pd]
    return matches, unmatched_gt, unmatched_pd

# ===================== עזר: הורדה/ייבוא מודל וטעינת משקלים =====================





def _force_usercontent(url: str) -> str:
    import re
    # מוציאים FILE_ID גם מלינק /d/<id>/ וגם מ־id=<id>
    m = re.search(r'id=([A-Za-z0-9_-]+)', url)
    if not m:
        m = re.search(r'/d/([A-Za-z0-9_-]+)(/|$)', url)
    fid = m.group(1) if m else None
    if fid:
        return f"https://drive.usercontent.google.com/uc?id={fid}&export=download"
    return url

import re, requests

def _extract_file_id(url_or_id: str) -> str | None:
    """מקבל קישור דרייב או ID ומחזיר File ID תקין."""
    # כבר ID נקי?
    if re.fullmatch(r"[A-Za-z0-9_-]{20,}", url_or_id):
        return url_or_id
    # פורמטים נפוצים:
    m = re.search(r"id=([A-Za-z0-9_-]+)", url_or_id)
    if not m:
        m = re.search(r"/d/([A-Za-z0-9_-]+)(?:/|$)", url_or_id)
    return m.group(1) if m else None

def _download_binary1(url_or_id: str) -> bytes:
    """
    מוריד קובץ בינארי (כמו weights.pt) מ-Google Drive (ID או URL) באמצעות gdown
    ומחזיר bytes.
    """
    with tempfile.NamedTemporaryFile(delete=False, suffix=".bin") as tmp:
        tmp_path = tmp.name

    if "drive.google.com" not in url_or_id and "http" not in url_or_id:
        url = f"https://drive.google.com/uc?export=download&id={url_or_id}"
    else:
        url = url_or_id

    gdown.download(url, tmp_path, quiet=True)

    with open(tmp_path, "rb") as f:
        return f.read()

def _download_binary(url_or_id: str) -> bytes:
    """
    מוריד קובץ בינארי (כמו weights.pt) מ-Google Drive (ID או URL) באמצעות gdown
    ומחזיר bytes.
    """
    with tempfile.NamedTemporaryFile(delete=False, suffix=".bin") as tmp:
        tmp_path = tmp.name

    if "drive.google.com" not in url_or_id and "http" not in url_or_id:
        url = f"https://drive.google.com/uc?export=download&id={url_or_id}"
    else:
        url = url_or_id

    gdown.download(url, tmp_path, quiet=True)

    with open(tmp_path, "rb") as f:
        return f.read()


def _gdrive_download_bytes(url_or_id: str, timeout=300) -> bytes:
    """
    מוריד קובץ מ-Google Drive באופן חסין:
    1) ניסיון דרך usercontent (לרוב מספיק)
    2) אם מתקבל HTML, זרימת confirm-token של Drive
    """
    fid = _extract_file_id(url_or_id) or url_or_id
    sess = requests.Session()

    # ניסיון 1: usercontent (ישיר)
    u1 = f"https://drive.usercontent.google.com/uc?id={fid}&export=download"
    r = sess.get(u1, timeout=timeout, allow_redirects=True)
    ct = (r.headers.get("Content-Type") or "").lower()
    if ("text/html" not in ct) and (not r.text.lstrip().startswith("<!DOCTYPE html")):
        r.raise_for_status()
        return r.content

    # ניסיון 2: confirm-token flow
    u2 = "https://drive.google.com/uc?export=download"
    r = sess.get(u2, params={"id": fid}, timeout=timeout, allow_redirects=True)
    token = None
    # טוקן נמצא לעיתים בעוגיות בשם download_warning/confirm
    for k, v in r.cookies.items():
        if k.startswith("download_warning") or k == "confirm":
            token = v
            break
    if not token:
        # לפעמים מגיע בתוך HTML
        m = re.search(r"confirm=([0-9A-Za-z_]+)", r.text)
        token = m.group(1) if m else None

    params = {"id": fid}
    if token:
        params["confirm"] = token
    r2 = sess.get(u2, params=params, timeout=timeout, allow_redirects=True)
    ct2 = (r2.headers.get("Content-Type") or "").lower()
    if "text/html" in ct2 and r2.text.lstrip().startswith("<!DOCTYPE html"):
        raise RuntimeError("Drive still returned HTML page (no raw file). Check sharing & link.")
    r2.raise_for_status()
    return r2.content











def infer_nodules(volume_np, model, device):
    import numpy as np, torch
    vol = volume_np.astype(np.float32)
    vmin, vmax = float(vol.min()), float(vol.max())
    if vmax <= vmin: vmax = vmin + 1.0
    vol = (vol - vmin) / (vmax - vmin)
    t = torch.from_numpy(vol[None, None, ...]).to(device=device, dtype=torch.float32)

    model.eval()
    with torch.no_grad():
        out = model(t, mode="eval")  # ה-forward של המודל המלא

    has_nodule = bool((out.get("has_nodule_detected", torch.tensor(0)) > 0).item())
    if not has_nodule:
        return np.zeros((0, 5), dtype=np.float32)

    cz, cy, cx, rz, ry, rx = out["best_pred"][0].detach().cpu().numpy()
    z = y = x = 128.0
    cz_v, cy_v, cx_v = cz * z, cy * y, cx * x
    diam_v = 2.0 * max(rz * z, ry * y, rx * x)
    return np.array([[1.0, cz_v, cy_v, cx_v, diam_v]], dtype=np.float32)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def load_remote_full_model(weights_url_or_id: str):
    import torch, tempfile

    w_bytes = _download_binary(weights_url_or_id)

    with tempfile.NamedTemporaryFile(delete=False, suffix=".pth") as wf:
        wf.write(w_bytes)
        w_path = wf.name
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # 💥 כאן השינוי הקריטי: weights_only=False
    model = torch.load(
        w_path,
        map_location=device,
        weights_only=False  # ← חובה כשמטעינים FULL MODEL
    )

    if not isinstance(model, torch.nn.Module):
        raise RuntimeError("הקובץ אינו FULL MODEL (torch.nn.Module).")
    model.to(device).eval()
    return model, device

def load_remote_full_model1(weights_url_or_id: str):
    import torch, tempfile

    w_bytes = _download_binary(weights_url_or_id)

    with tempfile.NamedTemporaryFile(delete=False, suffix=".pth") as wf:
        wf.write(w_bytes)
        w_path = wf.name

    obj = torch.load(w_path, map_location="cpu")

    if not isinstance(obj, torch.nn.Module):
        raise RuntimeError("הקובץ אינו FULL MODEL.")

    model = obj
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device).eval()

    return model, device


def try_model_infer(volume_np: np.ndarray) -> np.ndarray | None:
    try:
        #model = load_remote_full_model(FULL_MODEL_ID)
        model, device = load_remote_full_model(FULL_MODEL_ID)

        #model = load_full_model_from_drive(FULL_MODEL_ID)
        #model = load_full_model_from_url(FULL_MODEL_URL)  # טעינה מקובץ מודל מלא
        with torch.no_grad():
            return infer_nodules(volume_np, model, device)
    except Exception as e:
        st.warning(f"Model inference skipped: {e}")
        return None


# ... כל העזרות של המודל, infer_nodules, try_model_infer וכו' ...

# ============================================================
# 🔹 פונקציית אימון backend – רצה ברקע כשלוחצים Start Training
# ============================================================
from torch.utils.data import DataLoader  # ← לוודא שזה קיים איפשהו למעלה





# תקוע כאן
def try_model_infer_old(volume_np: np.ndarray) -> np.ndarray | None:
    """
    מריץ אינפרנס עם המודל המקומי + משקולות מרחוק בזרימה החסינה.
    """
    try:
        model, device = init_model_with_robust_remote_weights(WEIGHTS_URL)
        with torch.no_grad():
            return infer_nodules(volume_np, model, device)
    except Exception as e:
        st.warning(f"Model inference skipped: {e}")
        return None



# ===================== מסכים =====================
def render_home():

    st.markdown("<div class='center'>", unsafe_allow_html=True)
    st.markdown("# Lung nodule detection and classification system.")
    st.markdown("## By: Sharon Hanoked")
    st.markdown("### Supervised By Dr. Maya Herman")
    st.markdown("</div>", unsafe_allow_html=True)
    st.markdown("<div class='hr'></div>", unsafe_allow_html=True)

    c1, c2, c3 = st.columns([1,1,1])
    with c1:
        if st.button("📘 USER GUIDE", use_container_width=True):
            st.session_state.page = "guide"
            st.rerun()
    with c2:
        if st.button("🛠️ ADMIN", use_container_width=True):
            st.session_state.page = "admin"
            st.rerun()
    with c3:
        if st.button("👤 USER", use_container_width=True):
            st.session_state.page = "user"
            st.rerun()


def render_admin():
    st.markdown("## ADMIN")
    st.caption("")

    c1, c2 = st.columns([1, 1])
    with c1:
        if st.button("📈 System maintenance", use_container_width=True):
            st.session_state.page = "train"
            st.rerun()
    with c2:
        if st.button("🧪 Analiysis CT image", use_container_width=True):
            st.session_state.page = "test"
            st.rerun()

    st.markdown("<div class='hr'></div>", unsafe_allow_html=True)

    # כפתור Back בלי רקע
    st.markdown('<div class="back-btn">', unsafe_allow_html=True)
    if st.button("⬅️ Back to Home", type="secondary"):
        st.session_state.page = "home"
        st.rerun()
    st.markdown('</div>', unsafe_allow_html=True)

def render_user():
    st.markdown("## ")

    render_test()

def render_guide():
    st.markdown("## User Guide : Lung nodule detection and classification LUNA16 Challenge")
    st.markdown("*(Base of Luna 16 Grand Challenge)*")
    st.markdown(
        """
     A user-friendly interface for viewing 3D lung CT volumes (NPY, 128×128×128).
     The system automatically analyzes the scan to detect and mark possible lung nodules, indicates whether a nodule is present or not, and shows its exact location.
     Two main image planes — **Axial** and **Coronal** — are displayed for clear visualization.
     Results can also be compared with Ground Truth annotations to evaluate accuracy.
            """
        )


    st.markdown("### Supported files")
    st.write("- **Volume (required):** NPY, shape [Z, Y, X] = 128×128×128")
    st.write("- **Ground Truth (optional):** NPY, N×5 — [class, z, y, x, diameter]")
    st.markdown("### Image analysis colors")
    st.write("- **Green** = Ground Truth")
    st.write("- **Red** = Prediction (Model)")
    st.markdown("### User options")
    st.write(
        "- **Quick check:** Upload the volume; the app states if a nodule exists. "
        "If yes, it draws a bounding box and allows save/download.\n"
        "- **Compare with GT:** Upload volume + GT; the app reports presence in GT and Model, "
        "shows TP/FP/FN/TN, and overlays boxes (Green=GT, Red=Model)."
    )
    st.markdown("### Admin")
    st.write("Train/run the model in the system. Adjustable parameters: Learning rate, Epochs.")
    st.markdown("<div class='hr'></div>", unsafe_allow_html=True)
    if st.button("⬅️ Back to Home", type="secondary"):
        st.session_state.page = "home"
        st.rerun()

def render_train_placeholder():
    st.markdown("## System maintenance")
    st.markdown("Use this panel to configure and start model training.")
    st.markdown("---")

    # ממרכזים את כל האלמנטים
    col_spacer1, col_main, col_spacer2 = st.columns([1, 2, 1])
    with col_main:
        st.markdown("### 🧠 Training Parameters")

        # טופס הגדרות
        learning_rate = st.number_input(
            "Learning rate",
            min_value=1e-6,
            max_value=1.0,
            value=0.001,
            format="%.6f"
        )
        epochs = st.number_input(
            "Epochs",
            min_value=1,
            max_value=1000,
            value=2,
            step=1
        )

        st.markdown("---")

        # כפתור אימון במרכז
        train_button_center = st.columns([1, 1, 1])[1]
        with train_button_center:
            if st.button("🚀 Start Training", use_container_width=True):
                st.info("⏳ Training is running… please wait. This may take time.")

                # 🟣 הרצת האימון בפועל
                history = run_training_only_train(
                    num_epochs=2,
                    learning_rate=float(learning_rate),

                )

                # שמירת הגדרות + היסטוריה ל-session_state
                st.session_state["train_history"] = history
                st.session_state["train_config"] = {
                    "learning_rate": float(learning_rate),
                    "epochs": 2,
                }

                st.success("✔ Training finished!")
                st.session_state.page = "train_results"
                st.rerun()

    st.markdown("---")

    # כפתור חזרה בשורה התחתונה, בצד שמאל
    back_col1, _, _ = st.columns([1, 3, 1])
    with back_col1:
        if st.button("⬅️ Back to Admin", type="secondary"):
            st.session_state.page = "admin"
            st.rerun()



def render_train_results2():
    st.markdown("## 📊 Training results")

    history = st.session_state.get("train_history", None)
    config = st.session_state.get("train_config", {})

    if history is None or len(history.get("epoch", [])) == 0:
        st.info("לא נמצאו תוצאות אימון להצגה. הריצי Training קודם.")
        if st.button("⬅️ Back to Training", type="secondary"):
            st.session_state.page = "train"
            st.rerun()
        return

    epochs = history.get(
        "epoch",
        list(range(1, len(history["train_cls_loss"]) + 1))
    )

    # כותרת עם הפרמטרים ששימשו לאימון
    lr = config.get("learning_rate", None)
    ep = config.get("epochs", None)
    if lr is not None and ep is not None:
        st.write(f"**Learning rate:** `{lr:.6f}` &nbsp;&nbsp; | &nbsp;&nbsp; **Epochs:** `{ep}`")

    st.markdown("<div class='hr'></div>", unsafe_allow_html=True)

    # גודל אחיד לכל הגרפים
    FIG_SIZE = (6, 4)

    # =========================
    # 1) Classification Loss + BBox Loss – בשורה אחת
    # =========================
    col1, col2 = st.columns(2)

    with col1:
        fig1, ax1 = plt.subplots(figsize=FIG_SIZE)
        ax1.plot(epochs, history["train_cls_loss"], label="Train classification loss")
        ax1.plot(epochs, history["val_cls_loss"],   label="Val classification loss")
        ax1.set_title("Classification loss per epoch")
        ax1.set_xlabel("Epoch")
        ax1.set_ylabel("Loss")
        ax1.grid(True)
        ax1.legend()
        fig1.tight_layout()
        st.pyplot(fig1, use_container_width=True)

    with col2:
        fig2, ax2 = plt.subplots(figsize=FIG_SIZE)
        ax2.plot(epochs, history["train_bbox_loss"], label="Train bbox loss")
        ax2.plot(epochs, history["val_bbox_loss"],   label="Val bbox loss")
        ax2.set_title("BBox loss per epoch")
        ax2.set_xlabel("Epoch")
        ax2.set_ylabel("Loss")
        ax2.grid(True)
        ax2.legend()
        fig2.tight_layout()
        st.pyplot(fig2, use_container_width=True)

    st.markdown("<div class='hr'></div>", unsafe_allow_html=True)

    # =========================
    # 2) Accuracy
    # =========================
    fig3, ax3 = plt.subplots(figsize=FIG_SIZE)
    ax3.plot(epochs, history["train_acc"], label="Train accuracy")
    ax3.plot(epochs, history["val_acc"],   label="Val accuracy")
    ax3.set_title("Accuracy per epoch")
    ax3.set_xlabel("Epoch")
    ax3.set_ylabel("Accuracy")
    ax3.grid(True)
    ax3.legend()
    fig3.tight_layout()
    st.pyplot(fig3, use_container_width=True)

    st.markdown("<div class='hr'></div>", unsafe_allow_html=True)

    # =========================
    # 3) IoU + Dice – בשורה אחת
    # =========================
    col3, col4 = st.columns(2)

    with col3:
        fig4, ax4 = plt.subplots(figsize=FIG_SIZE)
        ax4.plot(epochs, history["train_iou"], label="Train IoU")
        ax4.plot(epochs, history["val_iou"],   label="Val IoU")
        ax4.set_title("IoU per epoch")
        ax4.set_xlabel("Epoch")
        ax4.set_ylabel("IoU")
        ax4.grid(True)
        ax4.legend()
        fig4.tight_layout()
        st.pyplot(fig4, use_container_width=True)

    with col4:
        fig5, ax5 = plt.subplots(figsize=FIG_SIZE)
        ax5.plot(epochs, history["train_dice"], label="Train Dice")
        ax5.plot(epochs, history["val_dice"],   label="Val Dice")
        ax5.set_title("Dice per epoch")
        ax5.set_xlabel("Epoch")
        ax5.set_ylabel("Dice")
        ax5.grid(True)
        ax5.legend()
        fig5.tight_layout()
        st.pyplot(fig5, use_container_width=True)

    st.markdown("<div class='hr'></div>", unsafe_allow_html=True)

    # כפתורי ניווט
    c1, c2, c3 = st.columns([1, 1, 1])
    with c1:
        if st.button("⬅️ Back to Training", type="secondary"):
            st.session_state.page = "train"
            st.rerun()
    with c2:
        if st.button("⬅️ Back to Admin", type="secondary", key="back_admin_from_results"):
            st.session_state.page = "admin"
            st.rerun()

def render_train_results():
    st.markdown("## 📊 Training results")

    history = st.session_state.get("train_history", None)
    config = st.session_state.get("train_config", {})

    if history is None or len(history.get("epoch", [])) == 0:
        st.info("לא נמצאו תוצאות אימון להצגה. הריצי Training קודם.")
        if st.button("⬅️ Back to Training", type="secondary"):
            st.session_state.page = "train"
            st.rerun()
        return

    # ציר X (אפוקים)
    epochs = history.get(
        "epoch",
        list(range(1, len(history["train_cls_loss"]) + 1))
    )

    # כותרת עם הפרמטרים ששימשו לאימון
    lr = config.get("learning_rate", None)
    ep = config.get("epochs", None)
    if lr is not None and ep is not None:
        st.write(f"**Learning rate:** `{lr:.6f}` &nbsp;&nbsp; | &nbsp;&nbsp; **Epochs:** `{ep}`")

    st.markdown("<div class='hr'></div>", unsafe_allow_html=True)

    # גודל בסיסי לכל הגרפים
    FIG_SIZE = (6, 4)

    # =========================
    # 1) Classification Loss + BBox Loss – בשורה אחת
    # =========================
    col1, col2 = st.columns(2)

    # ---- Classification loss ----
    with col1:
        fig1, ax1 = plt.subplots(figsize=FIG_SIZE)
        ax1.plot(epochs, history["train_cls_loss"], label="Train classification loss")
        ax1.plot(epochs, history["val_cls_loss"],   label="Val classification loss")
        ax1.set_title("Classification loss per epoch")
        ax1.set_xlabel("Epoch")
        ax1.set_ylabel("Loss")
        ax1.grid(True)
        ax1.legend()
        fig1.tight_layout()
        st.pyplot(fig1, use_container_width=True)

    # ---- BBox loss ----
    with col2:
        fig2, ax2 = plt.subplots(figsize=FIG_SIZE)
        ax2.plot(epochs, history["train_bbox_loss"], label="Train bbox loss")
        ax2.plot(epochs, history["val_bbox_loss"],   label="Val bbox loss")
        ax2.set_title("BBox loss per epoch")
        ax2.set_xlabel("Epoch")
        ax2.set_ylabel("Loss")
        ax2.grid(True)
        ax2.legend()
        fig2.tight_layout()
        st.pyplot(fig2, use_container_width=True)

    st.markdown("<div class='hr'></div>", unsafe_allow_html=True)

    # =========================
    # 2) Accuracy + Dice – בשורה אחת
    # =========================
    col3, col4 = st.columns(2)

    # ---- Accuracy ----
    with col3:
        fig3, ax3 = plt.subplots(figsize=FIG_SIZE)
        ax3.plot(epochs, history["train_acc"], label="Train accuracy")
        ax3.plot(epochs, history["val_acc"],   label="Val accuracy")
        ax3.set_title("Accuracy per epoch")
        ax3.set_xlabel("Epoch")
        ax3.set_ylabel("Accuracy")
        ax3.grid(True)
        ax3.legend()
        fig3.tight_layout()
        st.pyplot(fig3, use_container_width=True)

    # ---- Dice ----
    with col4:
        fig5, ax5 = plt.subplots(figsize=FIG_SIZE)
        ax5.plot(epochs, history["train_dice"], label="Train Dice")
        ax5.plot(epochs, history["val_dice"],   label="Val Dice")
        ax5.set_title("Dice per epoch")
        ax5.set_xlabel("Epoch")
        ax5.set_ylabel("Dice")
        ax5.grid(True)
        ax5.legend()
        fig5.tight_layout()
        st.pyplot(fig5, use_container_width=True)

    st.markdown("<div class='hr'></div>", unsafe_allow_html=True)

    # =========================
    # כפתורי ניווט
    # =========================
    c1, c2, c3 = st.columns([1, 1, 1])
    with c1:
        if st.button("⬅️ Back to Training", type="secondary"):
            st.session_state.page = "train"
            st.rerun()
    with c2:
        if st.button("⬅️ Back to Admin", type="secondary", key="back_admin_from_results"):
            st.session_state.page = "admin"
            st.rerun()


def render_train_placeholder1():
    st.markdown("## System maintenance")
    st.markdown("Use this panel to configure and start model training.")

    st.markdown("---")

    # ממרכזים את כל האלמנטים
    col_spacer1, col_main, col_spacer2 = st.columns([1, 2, 1])
    with col_main:
        st.markdown("### 🧠 Training Parameters")

        # טופס הגדרות
        learning_rate = st.number_input("Learning rate", min_value=1e-6, max_value=1.0, value=0.001, format="%.6f")
        epochs = st.number_input("Epochs", min_value=1, max_value=1000, value=50, step=1)
        #batch_size = st.number_input("Batch size", min_value=1, max_value=128, value=8, step=1)
        #optimizer = st.selectbox("Optimizer", ["Adam", "AdamW", "SGD", "RMSprop"], index=1)
        #loss_fn = st.selectbox("Loss function", ["BCEWithLogitsLoss", "FocalLoss", "SmoothL1Loss"], index=0)

        st.markdown("---")

        # כפתור אימון במרכז
        train_button_center = st.columns([1, 1, 1])[1]
        with train_button_center:
            if st.button("🚀 Start Training", use_container_width=True):
                st.success("Training started... (This is a placeholder demo.)")

    st.markdown("---")

    # כפתור חזרה בשורה התחתונה, בצד שמאל
    back_col1, _, _ = st.columns([1, 3, 1])
    with back_col1:
        if st.button("⬅️ Back to Admin", type="secondary"):
            st.session_state.page = "admin"
            st.rerun()

# בתחילת הקובץ פעם אחת (אם אין):
if "test_step" not in st.session_state:
    st.session_state["test_step"] = "form"


def render_test():
    step = st.session_state.get("test_step", "form")

    # ===== שלב 1: טופס העלאה באמצע, ללא Options =====
    if step == "form":
        st.markdown("## Image analysis – Upload")

        # --- NPY Volume row (label + uploader באותה שורה) ---
        c1, c2 = st.columns([1, 2])
        with c1:
            st.markdown("**Enter 3D CT Image size 128*128*128**")
        with c2:
            vol_file = st.file_uploader(
                label=" ", type=["npy"], key="vol_up", label_visibility="collapsed"
            )

        # --- labels.npy row ---
        c3, c4 = st.columns([1, 2])
        with c3:
            st.markdown("**Enter avaiiable true analyzed results – (Optional)**")
        with c4:
            lbl_file = st.file_uploader(
                label=" ", type=["npy"], key="lbl_up", label_visibility="collapsed"
            )

        # --- preds.npy row (אם את רוצה להשאיר; אפשר למחוק את הבלוק הזה) ---
        #c5, c6 = st.columns([1, 2])
        #with c5:
        #    st.markdown("**preds.npy (Model, N×5) – (Optional)**")
        #with c6:
        #    pd_file = st.file_uploader(
        #        label=" ", type=["npy"], key="pd_up", label_visibility="collapsed"
        #    )

        # --- כפתורים: BACK משמאל למטה, ANALYZE ממורכז ---
        st.markdown("---")
        left, center, right = st.columns([1, 1, 1])

        with left:
            if st.button("⬅️ Back to Home", type="secondary", key="back_home_upload"):
                st.session_state.page = "home"
                st.session_state.pop("test_data", None)
                st.session_state["test_step"] = "form"
                st.rerun()

        with center:
            can_run = vol_file is not None
            if st.button("▶️ Analyze", use_container_width=True, disabled=not can_run, key="analyze_btn"):
                import numpy as np
                try:
                    vol = np.squeeze(np.load(vol_file))
                    labels_np = np.load(lbl_file) if lbl_file is not None else None
                    preds_np=None
                except Exception as e:
                    st.error(f"File read error: {e}")
                    return
                if vol.ndim != 3:
                    st.error(f"Expected 3D volume. Got shape={vol.shape}")
                    return

                # ברירות מחדל כי אין Options במסך:
                iou_thr = 0.10
                full_width = True
                show_headers = False

                st.session_state["test_data"] = dict(
                    vol=vol, labels_np=labels_np, preds_np=None,
                    iou_thr=iou_thr, full_width=full_width, show_headers=show_headers
                )
                st.session_state["test_step"] = "results"
                st.rerun()

        # תא ריק כדי לשמור על הפריסה
        with right:
            st.write("")

    # ===== שלב 2: תוצאות (כמו שהיה, רק עם ברירות מחדל) =====
    else:
        st.markdown("## Image analysis – Results")

        td = st.session_state.get("test_data")
        if td is None:
            st.session_state["test_step"] = "form"
            st.rerun()
            return

        vol        = td["vol"]
        labels_np  = td["labels_np"]
        #preds_np   = td["preds_np"]A

        iou_thr    = td["iou_thr"]
        full_width = td["full_width"]
        show_headers = td["show_headers"]

        # === חדש: אם לא הועלה preds.npy – ננסה להריץ אינפרנס אוטומטי מהמודל המרוחק ===
        preds_np = td.get("preds_np", None)
        # אם לא הועלה preds.npy – מריצות אינפרנס מקומי להדפסה/בדיקה (ללא הורדה)
        if preds_np is None:
            preds_np = try_model_infer(vol)
            st.session_state["test_data"]["preds_np"] = preds_np

        import numpy as np
        #st.markdown("#### 🔎 Console mirror (העתק ללוג + תצוגה כאן)")

        if preds_np is None:
            st.text("preds_np = None (אין פלט מהמודל)")
        #else:
        #    st.text(f"type: {type(preds_np)}")
        #    if isinstance(preds_np, np.ndarray):
        #        st.text(f"shape: {preds_np.shape}, dtype: {preds_np.dtype}")
        #        st.code(np.array2string(
        #            preds_np, precision=3, threshold=10**9, max_line_width=200
        #        ))
        #    else:
        #        st.text(f"value: {preds_np}")


        ###

        # נשמור בזיכרון כדי שלא נריץ שוב ב-refresh
        st.session_state["test_data"]["preds_np"] = preds_np

        Z, Y, X = vol.shape
        gt_boxes, order_gt = parse_boxes(labels_np, Z, Y, X)
        pd_boxes, order_pd = parse_boxes(preds_np,  Z, Y, X)

        # --- הצגת Yes/No ברור לזיהוי נודולה ע"י המודל ---
        detected = len(pd_boxes) > 0
        st.markdown(f"### Nodule detected: {'✅ Yes' if detected else '❌ No'}")

        #st.caption(
        #    f"Volume: Z={Z}, Y={Y}, X={X} | dtype={vol.dtype} | "
        #    f"GT: {len(gt_boxes)} (order {order_gt.upper()}) | "
        #    f"Preds: {len(pd_boxes)} (order {order_pd.upper()})"
        #)

        has_gt, has_pd = len(gt_boxes) > 0, len(pd_boxes) > 0
        if not has_gt and not has_pd:
            st.success("TN – No nodule in GT and no detection in model.")
            st.markdown("<div class='hr'></div>", unsafe_allow_html=True)
        elif not has_gt and has_pd:
            st.warning("FP – No nodule in GT but model detected. (Per your request images not shown)")
            st.markdown("<div class='hr'></div>", unsafe_allow_html=True)
        elif has_gt and not has_pd:
            st.error("FN – Nodule in GT but no detection in model.")
        #else:
        #    #matches, un_gt, un_pd = match_greedy(gt_boxes, pd_boxes, iou_thr=iou_thr)
        #    #st.success(f"TP – Matches: TP={len(matches)}, FP={len(un_pd)}, FN={len(un_gt)} (IoU≥{iou_thr}).")
        #    st.success("**TP** – A nodule was detected both in the ground-truth and in the model.")

        else:
            # יש גם GT וגם Preds → נבדוק התאמות (TP) לפי IoU
            matches, un_gt, un_pd = match_greedy(gt_boxes, pd_boxes, iou_thr=iou_thr)

            if len(matches) > 0:
                # חישוב IoU ו-Dice לכל ההתאמות
                ious = [m[2] for m in matches]  # iou מכל match
                mean_iou = sum(ious) / len(ious)

                # Dice = 2 * IoU / (1 + IoU)
                dices = [2 * i / (1 + i) for i in ious]
                mean_dice = sum(dices) / len(dices)
                st.success(
                    f"**TP** – A nodule was detected both in the ground-truth and in the model. "
                    f"| **IoU:** {mean_iou:.3f} | **Dice:** {mean_dice:.3f}"
                )



                st.success("**TP** – A nodule was detected both in the ground-truth and in the model.")
                st.write(f"**IoU:** {mean_iou:.3f}")
                st.write(f"**Dice:** {mean_dice:.3f}")

            else:
                # יש גם GT וגם Preds אבל בלי התאמה מעל הסף → בפועל FP+FN
                st.warning(
                    f"No matched boxes at IoU ≥ {iou_thr}. (GT={len(gt_boxes)}, Preds={len(pd_boxes)})"
                )


        # --- סיכום 4 המצבים (TP/FP/FN/TN) בצורה אחידה ---
        has_gt = len(gt_boxes) > 0
        has_pd = len(pd_boxes) > 0
        if not has_gt and not has_pd:
            st.success("**TN** – No nodule in GT and no detection in model.")
            st.markdown("<div class='hr'></div>", unsafe_allow_html=True)
        elif not has_gt and has_pd:
            st.warning("**FP** – Model detected a nodule but **GT has none**. (Per your request images not shown)")
            st.markdown("<div class='hr'></div>", unsafe_allow_html=True)
        elif has_gt and not has_pd:
            st.error("**FN** – GT has a nodule but **model found none**.")
        #else:
            # יש גם GT וגם Preds → נבדוק התאמות (TP) לפי IoU
            #matches, un_gt, un_pd = match_greedy(gt_boxes, pd_boxes, iou_thr=iou_thr)
            #if len(matches) > 0:
            #    st.success(f"**TP** – {len(matches)} matches (IoU ≥ {iou_thr}).  FP={len(un_pd)}, FN={len(un_gt)}")
            #else:
            # יש גם GT וגם Preds אבל בלי התאמות (בפועל: FP ו־FN במקביל)
            #st.warning(f"No matched boxes at IoU ≥ {iou_thr}. (GT={len(gt_boxes)}, Preds={len(pd_boxes)})")


        # בחירת פרוסות
        if has_gt:
            z_main = clamp(int(round(gt_boxes[0][0])), 0, Z-1)
            x_main = clamp(int(round(gt_boxes[0][2])), 0, X-1)
        else:
            z_main = clamp(int(round(pd_boxes[0][0])), 0, Z-1) if has_pd else 0
            x_main = clamp(int(round(pd_boxes[0][2])), 0, X-1) if has_pd else 0
          # תחילת בלוק 1
        # תחילת בלוק 1 — חדש
        # ============= Per-nodule views (separate GT & Model, outline-only, correct axes & smaller images) =============
        if has_gt or has_pd:
            #st.markdown("---")
            st.subheader("Per-nodule views (GT vs Model)")

            # שליטה בגודל תמונות
            IMG_WIDTH = 420  # הקטנת תמונות; אפשר לשנות ל-300/360 וכו'

            def get_axial(vol, z_idx):
                return slice_to_pil(vol[clamp(int(round(z_idx)), 0, Z-1)])

            def get_coronal(vol, x_idx):
                return slice_to_pil(vol[:, :, clamp(int(round(x_idx)), 0, X-1)])

            def draw_rect_outline1(img, cx, cy, diam, color):
                dr = ImageDraw.Draw(img)
                r = float(diam) / 2.0
                dr.rectangle([(cx - r, cy - r), (cx + r, cy + r)], outline=color, width=3)  # קונטור בלבד
            def draw_rect_outline(img, cx, cy, diam, color):
                dr = ImageDraw.Draw(img)
                r = float(diam) / 2.0
                x0, y0 = cx - r, cy - r
                x1, y1 = cx + r, cy + r
                # קונטור בלבד (ללא fill)
                dr.rectangle([(x0, y0), (x1, y1)], outline=color, width=1, fill=None)
            GREEN = (0, 255, 0)
            RED   = (255, 0, 0)

            # התאמות לפי IoU
            matches, un_gt, un_pd = match_greedy(gt_boxes, pd_boxes, iou_thr=iou_thr)
            match_map = {gi: (pi, iou) for (gi, pi, iou) in matches}

            if has_gt:
                # עבור כל GT – מציגים את ה-GT על פרוסות ה-GT שלו,
                # ואם יש התאמה – מציגים את המודל על הפרוסות של המודל (Z/X משלו!)
                for i, (zg, yg, xg, dg, clsg) in enumerate(gt_boxes, start=1):
                    zgi = clamp(int(round(zg)), 0, Z-1)
                    xgi = clamp(int(round(xg)), 0, X-1)

                    #st.markdown(f"### 🫁 Nodule {i} (GT) — diam={dg:.1f}")

                    # GT Axial (Z=zgi) — מציירים בקואורדינטות (xg, yg)

                    #img_gt_ax = get_axial(vol, zgi).copy()
                    #draw_rect_outline(img_gt_ax, xg, yg, dg, GREEN)
                    #st.image(
                    #    img_gt_ax, width=IMG_WIDTH,
                    #    caption=f"🟩 GT — Axial (Z={zgi}) • center (x={int(round(xg))}, y={int(round(yg))}, z={int(round(zg))})"
                    #)

                    # Model Axial על פרוסת Z של המודל (אם קיימת התאמה)

                    # Model Axial – תמיד מוצג, בלי IoU ובלי תנאי
                    #if len(pd_boxes) > 0:
                    #    zp, yp, xp, dp, _ = pd_boxes[0]
                    #    zpi = clamp(int(round(zp)), 0, Z-1)

                    #   img_md_ax = get_axial(vol, zpi).copy()
                    #    draw_rect_outline(img_md_ax, xp, yp, dp, RED)  # ✅ מצייר in-place, בלי השמה
                    #    #st.image(img_md_ax, width=IMG_WIDTH, caption=...)
                    #    st.image(
                    #        img_md_ax,
                    #        width=IMG_WIDTH,
                    #        caption=f"🟥 Model — Axial (Z={int(round(zp))}, Y={int(round(yp))}, X={int(round(xp))})"
                    #    )
                    #else:
                    #    st.info("No model predictions found.")
                    # --- Axial row: GT | Model ---
                    col_ax_gt, col_ax_md = st.columns(2)

                    # GT Axial (Z=zgi)
                    with col_ax_gt:
                        img_gt_ax = get_axial(vol, zgi).copy()
                        draw_rect_outline(img_gt_ax, xg, yg, dg, GREEN)
                        st.image(
                            img_gt_ax, width=IMG_WIDTH,
                            caption=f"🟩 GT — Axial (Z={zgi}) • center (x={int(round(xg))}, y={int(round(yg))}, z={int(round(zg))})"
                        )

                    # Model Axial
                    with col_ax_md:
                        if len(pd_boxes) > 0:
                            zp, yp, xp, dp, _ = pd_boxes[0]
                            zpi = clamp(int(round(zp)), 0, Z-1)
                            img_md_ax = get_axial(vol, zpi).copy()
                            draw_rect_outline(img_md_ax, xp, yp, dp, RED)
                            st.image(
                                img_md_ax,
                                width=IMG_WIDTH,
                                caption=f"🟥 Model — Axial (Z={int(round(zp))}, Y={int(round(yp))}, X={int(round(xp))})"
                            )
                        else:
                            st.info("No model predictions found.")


                    # GT Coronal (X=xgi) — בקואורדינטות (y,z) בגלל החתך בציר X
                    #img_gt_co = get_coronal(vol, xgi).copy()
                    #draw_rect_outline(img_gt_co, yg, zg, dg, GREEN)
                    #st.image(
                    #    img_gt_co, width=IMG_WIDTH,
                    #    caption=f"🟩 GT — Coronal (X={xgi}) • center (x={int(round(xg))}, y={int(round(yg))}, z={int(round(zg))})"
                    #)


                    # Model Coronal – תמיד מוצג, בלי IoU ובלי תנאים מוקדמים
                    #if len(pd_boxes) > 0:
                    #    zp, yp, xp, dp, _ = pd_boxes[0]
                    #    xpi = clamp(int(round(xp)), 0, X-1)

                    #    img_md_co = get_coronal(vol, xpi).copy()
                    #    draw_rect_outline(img_md_co, yp, zp, dp, RED)  # ✅

                    #    st.image(
                    #        img_md_co,
                    #        width=IMG_WIDTH,
                    #        caption=f"🟥 Model — Coronal (Z={int(round(zp))}, Y={int(round(yp))}, X={int(round(xp))})"
                    #    )
                    #else:
                    #    st.info("No model predictions found.")
                    # --- Coronal row: GT | Model ---
                    col_co_gt, col_co_md = st.columns(2)

                    # GT Coronal (X=xgi)
                    with col_co_gt:
                        img_gt_co = get_coronal(vol, xgi).copy()
                        draw_rect_outline(img_gt_co, yg, zg, dg, GREEN)
                        st.image(
                            img_gt_co, width=IMG_WIDTH,
                            caption=f"🟩 GT — Coronal (X={xgi}) • center (x={int(round(xg))}, y={int(round(yg))}, z={int(round(zg))})"
                        )

                    # Model Coronal
                    with col_co_md:
                        if len(pd_boxes) > 0:
                            zp, yp, xp, dp, _ = pd_boxes[0]
                            xpi = clamp(int(round(xp)), 0, X-1)
                            img_md_co = get_coronal(vol, xpi).copy()
                            draw_rect_outline(img_md_co, yp, zp, dp, RED)
                            st.image(
                                img_md_co,
                                width=IMG_WIDTH,
                                caption=f"🟥 Model — Coronal (Z={int(round(zp))}, Y={int(round(yp))}, X={int(round(xp))})"
                            )
                        else:
                            st.info("No model predictions found.")

                    st.markdown("---")

            # אם אין GT בכלל — מציגים את כל הנודולות שחזה המודל (כל אחת בנפרד, 2 פרוסות על הצירים של המודל)
            if not has_gt and has_pd:
                for i, (z, y, x, d, cls) in enumerate(pd_boxes, start=1):
                    zi = clamp(int(round(z)), 0, Z-1)
                    xi = clamp(int(round(x)), 0, X-1)
                    #st.markdown(f"### 🔎 Predicted Nodule {i} — diam={d:.1f}")

                    img_md_ax = get_axial(vol, zi).copy()
                    draw_rect_outline(img_md_ax, x, y, d, RED)
                    st.image(
                        img_md_ax, width=IMG_WIDTH,
                        caption=f"🟥 Model — Axial (Z={zi}) • center (x={int(round(x))}, y={int(round(y))}, z={int(round(z))})"
                    )

                    img_md_co = get_coronal(vol, xi).copy()
                    draw_rect_outline(img_md_co, y, z, d, RED)
                    st.image(
                        img_md_co, width=IMG_WIDTH,
                        caption=f"🟥 Model — Coronal (X={xi}) • center (x={int(round(x))}, y={int(round(y))}, z={int(round(z))})"
                    )

                    #st.markdown("---")
        # סוף בלוק 1 — חדש


        # סוף בלוק 1
        #st.markdown("---")
        l, m, r = st.columns([1, 1, 1])
        with l:
            if st.button("⬅️ Back to Upload", type="secondary", key="back_upload_results"):
                st.session_state["test_step"] = "form"
                st.rerun()
        with m:
            # מקום ריק כדי להשאיר את Back Home בצד שמאל
            st.write("")
        with r:
            # ריק
            st.write("")

        # Back Home הכי למטה, שמאל
        #bl, bm, br = st.columns([1, 1, 1])
        #with bl:
        #    if st.button("⬅️ Back to Home", type="secondary", key="back_home_results"):
        #        st.session_state.page = "home"
        #        st.session_state.pop("test_data", None)
        #        st.session_state["test_step"] = "form"
        #        st.rerun()



#######################

# ===================== Router =====================
if st.session_state.page == "home":
    render_home()
elif st.session_state.page == "admin":
    render_admin()
elif st.session_state.page == "user":
    render_user()
elif st.session_state.page == "guide":
    render_guide()
elif st.session_state.page == "train":
    render_train_placeholder()
elif st.session_state.page == "train_results":
    render_train_results()      # ← ← ← כאן הקריאה מתבצעת בפועל
elif st.session_state.page == "test":
    render_test()
else:
    render_home()